apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "0"
  creationTimestamp: null
  labels:
    cnv-test: utility
    tier: node
  name: utility
  namespace: cnv-tests-utilities
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cnv-test: utility
      tier: node
  template:
    metadata:
      creationTimestamp: null
      labels:
        cnv-test: utility
        tier: node
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - command:
        - /bin/bash
        - -c
        - echo ok > /tmp/healthy && sleep INF
        image: quay.io/openshift-cnv/qe-cnv-tests-net-util-container:centos-stream-9
        imagePullPolicy: IfNotPresent
        name: utility
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host
          name: host
        - mountPath: /host/run/openvswitch
          name: ovs-run
        - mountPath: /run/dbus/system_bus_socket
          name: dbus-socket
        - mountPath: /host/dev
          name: dev
        - mountPath: /host/etc
          name: etc
        - mountPath: /host/var
          name: var
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        privileged: true
      terminationGracePeriodSeconds: 0
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host
      - hostPath:
          path: /run/openvswitch
          type: ""
        name: ovs-run
      - hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
        name: dbus-socket
      - hostPath:
          path: /dev
          type: Directory
        name: dev
      - hostPath:
          path: /etc
          type: Directory
        name: etc
      - hostPath:
          path: /var
          type: Directory
        name: var
  updateStrategy:
    type: OnDelete
