name: Read Secret, Create File, and Verify (No Secret Printing)

on:
  push:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  PR_DESCRIPTION: ${{ github.event.head_commit.message }}

jobs:
  verify_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Pull Request Number
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "PR branch is: ${GITHUB_REF##*/}"
          echo "Another option: and ${PR_URL##*/}"

      - name: Verify file creation (without revealing content)
        run: |
          echo "PR title is: $PR_TITLE"
          echo "PR description is: $PR_DESCRIPTION"
