name: Read Secret, Create File, and Verify (No Secret Printing)

on:
  push:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  PR_TITLE: ${{ github.event.pull_request.title }}
  PR_DESCRIPTION: ${{ github.event.head_commit.message }}

jobs:
  verify_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Pull Request Number
        run: |
          echo "PR branch is: ${GITHUB_REF##*/}"
          echo "Another option: $BRANCH_NAME"

      - name: Verify file creation (without revealing content)
        run: |
          echo "PR title is: $PR_TITLE"
          echo "PR description is: $PR_DESCRIPTION"
