name: Read Secret, Create File, and Verify (No Secret Printing)

on:
  push:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  PR_DESCRIPTION: ${{ github.event.head_commit.message }}
  NUM: ${{ github.event.issue.number }}

jobs:
  verify_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Pull Request Number
        run: |
          echo "PR branch is: ${GITHUB_REF##*/}"
          echo "Another option $NUM"

      - name: Verify file creation (without revealing content)
        run: |
          echo "PR title is: $PR_TITLE"
          echo "PR description is: $PR_DESCRIPTION"
      
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: 1
          body-regex: '^.*my 1.*$'
      - run: |
          echo ${{ steps.fc.outputs.comment-id }}
          echo ${{ steps.fc.outputs.comment-body }}
          echo ${{ steps.fc.outputs.comment-author }}
          echo ${{ steps.fc.outputs.comment-created-at }}
