name: Capture Pull Request Title

on:
  pull_request:
    types: [closed]  # Trigger on pull request closure

jobs:
  save_title:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Pull Request Title
        id: get_title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
           echo The Title of your PR is $TITLE
           echo "$PR_TITLE" >> $GITHUB_OUTPUT
        
      - name: Save Title to File (optional)
        run: |
          mkdir -p output  # Create output directory if needed
          echo "${{ steps.get_title.outputs.PR_TITLE }}" > output/pr_title.txt
