name: Read Secret, Create File, and Verify (No Secret Printing)

on:
  push:

jobs:
  verify_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      pull_request:
   types: [opened, synchronize]

  print_title_of_pr:
    runs-on: ubuntu-20.04
    steps:
    - name : Print Title of PR
      run: echo The Title of your PR is ${{ github.event.pull_request.title }}

    - name: Get Pull Request Title
      id: get_title
      run: |
        echo "PR_TITLE=$(github.event.pull_request.title)" >> $GITHUB_OUTPUT

    - name: Save Title to File (optional)
      run: |
        mkdir -p output  # Create output directory if needed
        echo "${{ steps.get_title.outputs.PR_TITLE }}" > output/pr_title.txt

    - name: Read non-secret file content
      run: |
        cat output/pr_title.txt
